//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfumer.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PerfumerDataBaseEntities : DbContext
    {

        private static PerfumerDataBaseEntities _context;

        public static PerfumerDataBaseEntities GetContext()
        {
            if (_context == null)
                _context = new PerfumerDataBaseEntities();
            return _context;
        }
        public PerfumerDataBaseEntities()
            : base("name=PerfumerDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductDB> ProductDB { get; set; }
        public virtual DbSet<SellersDB> SellersDB { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeamsDB> TeamsDB { get; set; }
        public virtual DbSet<WarehouseDB> WarehouseDB { get; set; }
    }
}
