//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfumer.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDB
    {
        public int C_id { get; set; }
        public string nameTitle { get; set; }
        public string article { get; set; }
        public string description { get; set; }
        public Nullable<bool> isvalid { get; set; }
        public Nullable<int> id_seller { get; set; }
        public string status { get; set; }
    
        public virtual SellersDB SellersDB { get; set; }
    }
}
