//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfumer.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsDB
    {
        public int C_id { get; set; }
        public string lastName { get; set; }
        public string fastName { get; set; }
        public string post { get; set; }
        public Nullable<bool> role { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    }
}
