//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfumer.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseDB
    {
        public int C_id { get; set; }
        public string titleName { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public string responsible { get; set; }
        public string phone { get; set; }
    }
}
